Repository xebialabs/xl-up-blueprint, pull requests merged in 2020-03, with the labels that each got.

#105 LOVE-1421
  integration-tests/test-cases/custom-docker-registry/test-eks-xld-xlr-mon-hybrid-cluster.yaml
  integration-tests/test-cases/custom-docker-registry/test-gke-xld-xlr-mon-hybrid-cluster.yaml
  integration-tests/test-cases/external-db/test-eks-xld-xlr-mon-mon-hybrid-cluster.yaml
  integration-tests/test-cases/external-db/test-gke-xld-xlr-mon-hybrid-cluster.yaml
  integration-tests/test-cases/k8s-token-auth/test-gke-xld-xlr-mon-hybrid-cluster.yaml
  integration-tests/test-cases/provisioned-db/test-azure-xld-xlr-mon-hybrid-cluster.yaml
  integration-tests/test-cases/provisioned-db/test-eks-xld-xlr-mon-hybrid-cluster.yaml
  integration-tests/test-cases/provisioned-db/test-gke-xld-xlr-mon-hybrid-cluster.yaml
  xl-up/blueprint.yaml
  xl-up/generated_answers.yaml.tmpl
  xl-up/xebialabs/kubernetes/efk-stack/elasticsearch/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/efk-stack/es-curator/cronjob.yaml.tmpl
  xl-up/xebialabs/kubernetes/efk-stack/fluentd/daemonset.yaml.tmpl
  xl-up/xebialabs/kubernetes/efk-stack/kibana/dashboard-job.yaml.tmpl
  xl-up/xebialabs/kubernetes/efk-stack/kibana/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/pg-stack/grafana/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/pg-stack/grafana/importer-job.yaml.tmpl
  xl-up/xebialabs/kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/pg-stack/prometheus/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-deploy/external-db/active-active/xld-deployment-master.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-deploy/external-db/active-active/xld-deployment-worker.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-deploy/local-db/xld-deployment-single-node.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/aws-efs/aws-efs-deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/ha-proxy-ingress-controller/default-backend.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/ha-proxy-ingress-controller/ingress-controller.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/nfs-client-provisioner/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/postgresql/xl-postgresql.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/rabbitmq/xl-rabbitmq.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-release/external-db/active-active/xlr-deployment-active.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-release/local-db/xlr-deployment-single-node.yaml.tmpl
Labels: run-xl-up-pr

#112 LOVE-1475 Update to 9.6.0
  Jenkinsfile
Labels: run-xl-up-pr

#115 LOVE-1518 Fixed Jenkins test files for custom namespace
  integration-tests/test-cases/jenkins/eks-xld-xlr-mon-full.yaml
  integration-tests/test-cases/jenkins/gke-xld-xlr-mon-full.yaml
  integration-tests/test-cases/jenkins/on-prem-xld-xlr-mon-full-windows.yaml
  integration-tests/test-cases/jenkins/on-prem-xld-xlr-mon-full.yaml
Labels: run-xl-up-pr

#119 Love 1441
  .github/pull_request_template.md
  Jenkinsfile
  integration-tests/test-cases/azure-base-cn.yaml
  integration-tests/test-cases/azure-base.yaml
  integration-tests/test-cases/custom-docker-registry/test-aks-xld-xlr-mon.yaml
  integration-tests/test-cases/custom-docker-registry/test-eks-xld-xlr-mon.yaml
  integration-tests/test-cases/custom-docker-registry/test-gke-xld-xlr-mon.yaml
  integration-tests/test-cases/custom-docker-registry/test-local-xld-xlr.yaml
  integration-tests/test-cases/custom-docker-registry/test-on-prem-xld-xlr-mon.yaml
  integration-tests/test-cases/custom-namespace/test-azure-xld-xlr-mon.yaml
  integration-tests/test-cases/custom-namespace/test-eks-xld-xlr-mon.yaml
  integration-tests/test-cases/custom-namespace/test-gke-xld-xlr-mon.yaml
  integration-tests/test-cases/custom-namespace/test-local-xld-xlr.yaml
  integration-tests/test-cases/custom-namespace/test-on-prem-xld-xlr-mon.yaml
  integration-tests/test-cases/eks-base-cn.yaml
  integration-tests/test-cases/eks-base.yaml
  integration-tests/test-cases/gke-base-cn.yaml
  integration-tests/test-cases/gke-base.yaml
  integration-tests/test-cases/provisioned-db/test-azure-xld-xlr-mon.yaml
  integration-tests/test-cases/provisioned-db/test-eks-xld-xlr-mon.yaml
  integration-tests/test-cases/provisioned-db/test-gke-xld-xlr-mon.yaml
  integration-tests/test-cases/provisioned-db/test-local-xld-xlr.yaml
  integration-tests/test-cases/provisioned-db/test-on-prem-xld-xlr-mon.yaml
  xl-up/blueprint.yaml
  xl-up/generated_answers.yaml.tmpl
  xl-up/xebialabs/answers.yaml.tmpl
  xl-up/xebialabs/kubernetes/efk-stack/elasticsearch/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/efk-stack/es-curator/cronjob.yaml.tmpl
  xl-up/xebialabs/kubernetes/efk-stack/fluentd/daemonset.yaml.tmpl
  xl-up/xebialabs/kubernetes/efk-stack/kibana/dashboard-job.yaml.tmpl
  xl-up/xebialabs/kubernetes/efk-stack/kibana/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/pg-stack/grafana/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/pg-stack/grafana/importer-job.yaml.tmpl
  xl-up/xebialabs/kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/pg-stack/prometheus/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-deploy/external-db/active-active/xld-deployment-master.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-deploy/external-db/active-active/xld-deployment-worker.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-deploy/local-db/xld-deployment-single-node.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/aws-efs/aws-efs-deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/ha-proxy-ingress-controller/default-backend.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/ha-proxy-ingress-controller/ingress-controller.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/ha-proxy-ingress-controller/service-l7.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/nfs-client-provisioner/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/postgresql/xl-postgresql.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/rabbitmq/xl-rabbitmq.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-release/external-db/active-active/xlr-deployment-active.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-release/local-db/xlr-deployment-single-node.yaml.tmpl
Labels: run-xl-up-pr, same-branch-on-cli

#122 LOVE-1412
  integration-tests/test-cases/azure-base-cn.yaml
  integration-tests/test-cases/azure-base.yaml
  integration-tests/test-cases/custom-storage-classes/test-azure-xld-xlr-mon.yaml
  integration-tests/test-cases/custom-storage-classes/test-eks-xld-xlr-mon.yaml
  integration-tests/test-cases/custom-storage-classes/test-gke-xld-xlr-mon.yaml
  integration-tests/test-cases/custom-storage-classes/test-on-prem-xld-xlr-mon.yaml
  integration-tests/test-cases/eks-base-cn.yaml
  integration-tests/test-cases/eks-base.yaml
  integration-tests/test-cases/gke-base-cn.yaml
  integration-tests/test-cases/gke-base.yaml
  integration-tests/test-cases/jenkins/aks-xld-xlr-mon-full.yaml
  integration-tests/test-cases/jenkins/eks-xld-xlr-mon-full.yaml
  integration-tests/test-cases/jenkins/gke-xld-xlr-mon-full.yaml
  integration-tests/test-cases/jenkins/on-prem-xld-xlr-mon-full-windows.yaml
  integration-tests/test-cases/jenkins/on-prem-xld-xlr-mon-full.yaml
  integration-tests/test-cases/provisioned-db/test-azure-xld-xlr-mon.yaml
  integration-tests/test-cases/provisioned-db/test-eks-xld-xlr-mon.yaml
  integration-tests/test-cases/provisioned-db/test-gke-xld-xlr-mon.yaml
  integration-tests/test-cases/provisioned-db/test-on-prem-xld-xlr-mon.yaml
  xl-up/blueprint.yaml
  xl-up/generated_answers.yaml.tmpl
  xl-up/xebialabs/answers.yaml.tmpl
  xl-up/xebialabs/kubernetes/efk-stack/elasticsearch/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/pg-stack/grafana/pvc.yaml.tmpl
  xl-up/xebialabs/kubernetes/pg-stack/prometheus/deployment.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-deploy/external-db/active-active/xld-deployment-worker.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-deploy/local-db/xld-deployment-single-node.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/postgresql/xl-postgresql.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/rabbitmq/xl-rabbitmq.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/xl-pvc/pvc-xld-export.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/xl-pvc/pvc-xlr-reports.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-release/local-db/xlr-deployment-single-node.yaml.tmpl
  xl-up/xebialabs/xl-k8s-foundation.yaml.tmpl
Labels: run-xl-up-pr, same-branch-on-cli

#124 Love 1450
  integration-tests/test-cases/azure-base-cn.yaml
  integration-tests/test-cases/azure-base.yaml
  integration-tests/test-cases/eks-base-cn.yaml
  integration-tests/test-cases/eks-base.yaml
  integration-tests/test-cases/external-ingress/test-azure-xld-xlr-mon.yaml
  integration-tests/test-cases/external-ingress/test-eks-xld-xlr-mon.yaml
  integration-tests/test-cases/external-ingress/test-gke-xld-xlr-mon.yaml
  integration-tests/test-cases/external-ingress/test-on-prem-xld-xlr-mon.yaml
  integration-tests/test-cases/gke-base-cn.yaml
  integration-tests/test-cases/gke-base.yaml
  integration-tests/test-cases/jenkins/aks-xld-xlr-mon-full.yaml
  integration-tests/test-cases/jenkins/eks-xld-xlr-mon-full.yaml
  integration-tests/test-cases/jenkins/gke-xld-xlr-mon-full.yaml
  integration-tests/test-cases/jenkins/on-prem-xld-xlr-mon-full-windows.yaml
  integration-tests/test-cases/jenkins/on-prem-xld-xlr-mon-full.yaml
  xl-up/blueprint.yaml
  xl-up/generated_answers.yaml.tmpl
  xl-up/xebialabs/answers.yaml.tmpl
  xl-up/xebialabs/kubernetes/pg-stack/grafana/secret.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-deploy/external-db/active-active/xld-deployment-master.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-deploy/local-db/xld-deployment-single-node.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-k8s-foundation/xebialabs-service-internal.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-release/external-db/active-active/xlr-deployment-active.yaml.tmpl
  xl-up/xebialabs/kubernetes/xl-release/local-db/xlr-deployment-single-node.yaml.tmpl
  xl-up/xebialabs/xl-k8s-foundation.yaml.tmpl
Labels: same-branch-on-cli
